---
tbl-colwidths: [10,70,20]
from: markdown+emoji
---

# Program {#sec-program}

:bulb:: Keynote, :microphone:: Invited or contributing presentation, :clipboard:: Poster

:bulb: [The power of numeric evidence in science communication](#abs-peters) Ellen Peters

:bulb: [title](#abs-kadane) Joseph (Jay) Kadane

:bulb: [Communicating uncertainties about scientific evidence and health risks to the public during the COVID19 pandemic: a good idea?](#abs-timmermans) Danielle Timmermans

:microphone: [The Power of Emotion in Risk Communication](#abs-joffe) Helen Joffe

:microphone: [Uncertainty, expertise, and persuasion: A replication and extension of Karmarkar and Tormala (2010)](#abs-lohre) Erik Løhre et al

:microphone: [Experiences from testing methods for decision making under deep uncertainty (DMDU) in relation to climate change adaptation in Swedish municipalities](#abs-carstens) Christoffer Carstens

:microphone: [Elicitation under severe uncertainty in risk analysis: a non-betting interpretation of bounded probability](#abs-troffaes) Matthias Troffaes

:microphone: [(tentative) Navigating deep uncertainty](#abs-logan) Tom Logan

:microphone: [Climate adaptation in multi-level governance systems: security, risk, or normal politics?](#abs-barquet) Karina Barquet

:microphone: [Assessing large-scale climate adaptation interventions from the perspective of intergenerational justice: Preserving options and avoiding irreversible planetary loss](#abs-doorn) Neelke Doorn

:microphone: [Elicitation of structured expert judgements from groups – protocols, experiences and interpreting the results](#abs-wilson) Kevin Wilson

:microphone: [Exploring Customer Loyalty Changes Amid Climate Activism Targeting Oil Companies and Banks](#abs-diaz) Aitor Marcos Diaz

:microphone: [Probabilistic evaluation of forensic evidence in Sweden](#abs-nordgaard) Anders Nordgaard

:microphone: TBC

:clipboard: [Distributing responsibility for managing uncertain issues - on what ethical grounds?](#abs-knaggard) Åsa Knaggård

:clipboard: [Prioritising Risk Education in Secondary Schools: Perspectives, Practicalities, and Progress](#abs-duckett) Sarah Duckett

:clipboard: [Translating predictive distributions into informative priors](#abs-saxena) Isha Saxena

:clipboard: Submission for posters is still open

# Schedule

| Date    | Time  |                                       |
|---------|-------|---------------------------------------|
| 11 June | 14.00 | Welcome                               |
|         |       | :bulb: Keynote                        |
|         |       | :microphone: Contributing talks       |
|         |       | :clipboard: Poster highlights         |
|         | 17.00 | Networking reception & poster session |
|         | 19.00 | Dinner                                |
| 12 June | 10.30 | :bulb: Keynote                        |
|         |       | :microphone: Contributing talks       |
|         | 13.00 | Lunch                                 |
|         | 14.00 | :bulb: Keynote                        |
|         |       | :microphone: Contributing talks       |
|         | 17.00 | Closing of the conference             |

# Abstracts Keynote talks

<!-- #### Title \| Author, Affiliation {#abs-lastname} -->

<!-- [:arrow_up_small:](#sec-program) -->

#### The power of numeric evidence in science communication \| Ellen Peters, University of Oregon, USA {#abs-peters}

Challenges exist in presenting numeric information in science communication. For example, public innumeracy—and experts’ concerns about providing numbers—suggest not showing them. On the other hand, people often prefer getting them and their provision can increase comprehension, trust, engagement, and healthy behaviors while reducing risk overestimates and supporting decision-maker autonomy. Presenting numeric facts without considering their comprehensibility and usability though is like throwing good money after bad. Thus, we’ll briefly examine three general strategies for nurturing comprehension and use of numbers in other persons. [:arrow_up_small:](#sec-program)

#### Title \| Joseph (Jay) Kadane, Carnegie Mellon University, USA {#abs-kadane}

Abstract in prep

#### Communicating uncertainties about scientific evidence and health risks to the public during the COVID19 pandemic: a good idea? \| Danielle Timmermans, Amsterdam Public Health research institute, The Netherlands {#abs-timmermans}

Despite major uncertainties at the beginning of the COVID19 pandemic, communications to the public in the Netherlands often lacked references to the uncertainty of scientific knowledge about e.g. the contagiousness of the virus. Only later in the pandemic did politicians and experts more often mention the associated risks and uncertainties. This may have to do with the perception of politicians and experts that the public cannot deal with uncertainties and therefore they played down the uncertainty. Furthermore, uncertainty about scientific evidence may not have been relevant to policy decisions on measures to control the pandemic at specific phases of the pandemic. I will discuss the results of our recent interview study with Dutch policymakers, scientific experts and communications professionals involved in advising politicians on how to deal with the pandemic. [:arrow_up_small:](#sec-program)

# Abstracts Invited and contributing talks

#### The Power of Emotion in Risk Communication \| Helene Joffe, University College London, UK {#abs-joffe}

There is much debate about the power of numeric information in conveying risk. If we are to avoid statistics, what other forms of communication work? Examples of successful risk communications will be explored in this talk. They draw on the persuasion literature, which is heavily used by governments in health and safety campaigning. In avoiding statistical ways of conveying risk, how is it conveyed? The answer is often via emotive themes – with surprise and solidarity as more effective than negative emotive material such as that eliciting fear, though disgust has equivocal effects. Certain visual depictions are also effective. These pathways to successful risk communication require further development and this talk will explore and critically evaluate existing risk campaigns and the literature on their effects. [:arrow_up_small:](#sec-program)

#### Uncertainty, expertise, and persuasion: A replication and extension of Karmarkar and Tormala (2010) \| Erik Løhre et al BI Norwegian Business School, Norway {#abs-lohre}

<!--#Erik Løhre (presenter), Subramanya Prasad Chandrashekar, Lewend Mayiwar, Thorvald Hærem  -->

If you are trying to persuade someone, expressing your opinion with certainty intuitively seems like a good strategy to maximize your influence. However, Karmarkar and Tormala (2010) found that the effectiveness of this tactic depends on expertise. In three experiments, Karmarkar and Tormala found support for an incongruity hypothesis, whereby non-expert sources can gain interest and influence by expressing certainty, while expert sources can increase persuasion by expressing uncertainty. In this Registered Report, we conducted a high-powered (N = 1018) direct replication of Experiment 2 by Karmarkar and Tormala (2010). In a consumer behavior context, the original study examined whether source expertise moderated the positive effect of source certainty on the persuasive impact of a restaurant recommendation. The present replication failed to find support for the incongruity hypothesis, ηp2 =.00 \[.00, .02\]: expressing certainty had a positive but non-significant effect for non-experts, Cohen’s d = 0.10 \[-0.10, 0.34\], and a positive effect for experts, Cohen’s d = 0.28 \[0.03, 0.52\]. Instead, the results supported the competing confidence heuristic hypothesis that expressed certainty would have a positive effect on persuasion, irrespective of source expertise, Cohen’s d = 0.18 \[0.01, 0.36\]. Extending the original work, we (1) controlled for the reason given for (un)certainty, and (2) examined need for closure as a potential individual difference moderator. The results indicated robust support for the confidence heuristic, but found that neither reason for (un)certainty nor need for closure moderated the effect. All materials, data, and code are available in the [preprint](https://osf.io/hbjyv/?view_only=4fa551dff0574e0b9c24f80c1d18cf4a) [:arrow_up_small:](#sec-program)

#### Experiences from testing methods for decision making under deep uncertainty (DMDU) in relation to climate change adaptation in Swedish municipalities \| Christoffer Carstens, Länsstyrelsen (County Administrative Board) Gävleborg, Sweden {#abs-carstens}

Strategic climate adaptation is characterized by long-term decisions where scientific support fails to give decision-makers full support (Hallegatte 2009). The uncertainties are large and, in many cases, impossible to reduce. The consequence is that many climate adaptation decisions must be made under "deep uncertainty," meaning situations in which there are uncertainties about either models, probabilities of outcomes, or how stakeholders value outcomes (Lempert et al. 2003, Marchau et al. 2019). The Swedish national strategy for climate change adaptation also highlights the need for addressing uncertainty, risk management and flexibility, without providing further guidance. Local decision makers often struggle to manage uncertainties within both the municipal practices and legal framework.

In the research program ROBUSTA (Robust decisions to manage climate risks in Sweden, 2015-2020) DMDU methods were both evaluated and tested within municipal spatial planning processes. The program developed into several implementation projects, in which actual tools were developed and tested, as well as new guidelines. In 2023 a new policy lab for climate adaptation was accepted, including the County Administrative Board of Gävleborg and all 10 municipalities within the county.

Experiences from the almost 10-year programs indicate that municipalities in general lack methodology, guidelines and experience from DMDU. Further, all implementation projects were considered helpful for municipal climate change adaptation; they provided opportunities for knowledge sharing and management of complexities between organizational boundaries as well as concrete methods for incorporating complex climate data into the decision-making process. Several possible obstacles for full-scale implementation were also identified, including regulatory and legal hindrances, as well as organizational challenges, related to both competence and resourses. [:arrow_up_small:](#sec-program)

#### Elicitation under severe uncertainty in risk analysis: a non-betting interpretation of bounded probability \| Matthias Troffaes, Durham University, UK {#abs-troffaes}

In this contribution, I will present a novel interpretation of bounded probability which is arguably more suitable for elicitation and communication of severe uncertainty in risk analysis. To do so, I propose an adjustment of Lindley's urn interpretation of probability to allow for infinite spaces and real-valued bounded expectations, which are ubiquitous in statistical analysis. I show this interpretation is mathematically equivalent to Williams's betting interpretation of lower previsions. This means that all the mathematical techniques and tools developed for lower previsions are completely accessible also under this new interpretation. I go through a small example in Bayesian elicitation and inference to show how this interpretation might work in practice. [:arrow_up_small:](#sec-program)

#### (tentative) Navigating deep uncertainty \| Tom Logan, University of Canterbury, New Zealand {#abs-logan}

The future is marked by unprecedented uncertainty, demanding a re-evaluation of how we make decisions. The challenges facing society today are complex and made up of layers of uncertainty, such as climate change, population dynamics, economic shifts, and rapid technological advancements. These layers compound, creating disagreement within scientific and planning communities, the very definition of deep uncertainty.

Traditional decision-making approaches, such as predict-and-act, are obsolete under deep uncertainty. These approaches rely on precise forecasts and probabilistic models that provide a false sense of certainty. They overlook the range of possible outcomes and downplay uncertainty.

To navigate deep uncertainty, new decision-making approaches based on the principle of robustness have emerged. However, these approaches were initially designed for non-urban contexts. Understanding their characteristics, strengths, and weaknesses can help decision-makers choose the right approach for their situation. Misapplying these approaches can lead to resource misallocation and failure to protect and provide for citizens.

The Society for Decision Making under Deep Uncertainty (DMDU) created a taxonomy to identify the characteristics of these new approaches. Using this information, approaches can be classed into two categories, approaches that create plans that adapt to dynamic, uncertain conditions, and approaches that analyse the robustness of the plans. Additionally, how a plan accounts for multiple hazards and dimensions of uncertainties was investigated. This informed the creation of the Approach Selection Key (ASK). ASK is a dichotomous key that guides decision-makers in selecting the most fitting approach for their specific situation.

Cities worldwide are starting their climate change adaptation processes without investigating uncertainties and what decision-making approaches are available to them. Relying on traditional methods and crafting static plans may result in over-adaptation and vulnerability to unforeseen developments. ASK provides decision-makers with a tool to select the most appropriate approach for their situation, leveraging, rather than ignoring uncertainty. [:arrow_up_small:](#sec-program)

#### Elicitation of structured expert judgements from groups – protocols, experiences and interpreting the results \| Kevin Wilson, Newcastle University, UK {#abs-wilson}

In this talk I will consider the elicitation of expert judgements in the form of probability distributions from groups of experts. I will review some of the main protocols used for this task in the context of some of my own elicitation experiences in the fields of food safety, climate resilience, energy modelling, healthcare and diagnostics. I will then propose an adaption to the popular probabilistic Delphi method – which aims to bring the experts towards consensus via anonymised information sharing over multiple rounds of judgements – via a Bayesian reconciliation step in place of aggregation of final distributions for each expert using an equally weighted linear pool. I provide some empirical comparisons to demonstrate why this may be a desirable approach, alongside some philosophical arguments. [:arrow_up_small:](#sec-program)

#### Assessing large-scale climate adaptation interventions from the perspective of intergenerational justice: Preserving options and avoiding irreversible planetary loss \| Neelke Doorn, Delft University of Technology, The Netherlands {#abs-doorn}

Most scholars working on climate change nowadays agree that justice requires that we not only take into consideration people currently alive (intragenerational justice) but also future generations (intergenerational justice). Where early philosophical discussions on intergenerational justice focused on the question whether we do indeed have obligations to future generations, current debates focus on what these obligations entail. The focus of this presentation is on climate adaptation and the question of how to account for ethical considerations with a temporal dimension. The aim is to explore which currencies for intergenerational distributive justice in climate adaptation can be consistently applied in existing frameworks that have been developed to guide environmental and climate-related decision-making and future actions. The focus will be on large-scale adaptive interventions. These interventions pose some specific challenges: they are often one-off interventions with little comparable examples to learn from, the conditions under which these interventions should function are largely unknown, posing both the risk of being too radical and doing too little, and the people bearing the consequences are future generations, whose preferences are difficult to assess. In this presentation, I will elaborate current conceptions of justice and map the three most common currencies of justice from the intragenerational justice literature. Discussion of these currencies suggests that intergenerational justice requires to preserve those things that provide people with a choice or option-space. Based on a discussion of two existing frameworks that have been developed to guide environmental and climate-related decision-making and future actions, the paper explores how these frameworks can be used to assess intergenerational aspects of large-scale climate adaptation interventions.[:arrow_up_small:](#sec-program)

#### Exploring Customer Loyalty Changes Amid Climate Activism Targeting Oil Companies and Banks \| Aitor Marcos Diaz, USC Wrigley Institute for Environment and Sustainability, USA {#abs-diaz}

The Activist's Dilemma trade-off occurs when activists resort to impactful but questionable actions, putting public support for their cause at risk. Based on the Activist’s Dilemma, our research posits that disruptive climate protests are less effective in undermining customer loyalty compared to moderate protests, contingent on the targeted company type. Companies less directly linked to the climate crisis (e.g., banks funding oil projects) might be more insulated from disruptive protests than those with direct links (e.g., oil companies).

Using a 2x2 survey experiment (N=400), we tested whether news about disruptive vs. moderate protests against companies planning new oil and gas developments influence customer loyalty toward those companies. We examine whether this relationship is mediated by perceptions of companies’ agency and ascription of responsibility regarding the climate crisis. Additionally, we explore whether the type of targeted company (bank vs. oil company) influences the mediation.

Results show that participants presented with the disruptive protest scenario were less willing to switch to another company. That is, moderate protests against companies were significantly more effective in eroding customer loyalty. A moderated mediation analysis revealed that the indirect effect of protest extremity on switching intentions—mediated by the perceived agency and ascription of responsibility—was negative and significant when banks were targeted, yet positive and non-significant for oil companies.

When banks are targeted by disruptive protests, participants’ perception of banks’ agency decreases, whereas a disruptive protest against an oil company does not alter the perceived role of oil companies conducting climate-harmful activities. These findings demonstrate that the shift in public opinion, predicted by the Activist’s Dilemma, becomes less relevant when the targeted company's agency and responsibility in the climate crisis are clearly associated with the environmental impact of their activity. [:arrow_up_small:](#sec-program)

#### Probabilistic evaluation of forensic evidence in Sweden \| Anders Nordgaard, Linneaus University, Sweden {#abs-nordgaard}

Forensic evidence has a very long history in legal proceedings. The traditional way of reporting results from forensic examinations has been to give a statement on the origin of recovered traces, based on a comparison of these traces with reference material from its suspected origin. Such a statement would typically be one of three: “identification”, “exclusion” and “inconclusive”. By identification is meant that in the forensic expert’s view, the recovered material comes from the suspected origin, by exclusion is meant that in the forensic expert’s view the recovered material does not come from the suspected origin, and by inconclusive is meant that the forensic expert cannot deem on whether it is an identification or an exclusion.

The National Forensic Centre (NFC) of the Swedish Police Authority does not use this way of reporting for the majority of its examinations. Instead, it is anticipated that a forensic examination cannot reach a final statement about the origin of a recovered material. There is more than just the forensic comparison of materials that is needed to reach such a statement. Instead, NFC assesses the probabilities of their forensic findings under different hypotheses stated on the origin of the recovered material. One of these hypotheses is the conjecture that comes from the preliminary investigation. The other hypotheses may be various alternatives to this conjecture. The assessed probabilities are used to assign a Bayes factor for the conjecture coming from the preliminary investigation.

The probabilities assessed are in most cases subjective, i.e. they are assessed based on experience and subject knowledge with the expert, and general experience within the global forensic community. However, they are normally not very precise and because the alternative hypotheses may be many, it is important to report probabilities that do not overstate the strength of the forensic findings. Therefore, a scale of conclusions is used to report the assigned Bayes factor, where the different scale levels correspond to intervals of the Bayes factor. [:arrow_up_small:](#sec-program)

#### Climate adaptation in multi-level governance systems: security, risk, or normal politics? \| Karina Barquet, Stockholm Environmental Institute, Sweden {#abs-barquet}

Using a securitization lens, this article delves into the discourse surrounding the climate crisis and its impact on the making and implementation of climate adaptation strategies in Sweden. The primary objective is to discern whether climate change is understood and addressed as a crisis within Swedish climate adaptation policy, examining its practical implications from national to local levels. Through a thorough review of key documents coupled with triangulated key informant interviews, we scrutinize the discourses employed to frame climate adaptation. Specifically, we assess whether these discourses align with threatification, riskification, or normal policy paradigms, and explore the actors and tools involved in creating this framing. Our findings illustrate the emergence of the climate crisis discourse and corresponding practices at various levels of governance, occasionally differing among administrative divisions and sectors. Nationally, climate adaptation is managed akin to any other policy domain. The formulation of objectives and priorities for climate adaptation takes place through centralized decision-making, then monitored through accountability mechanisms spanning national, subregional, and local levels. The national government maintains financial and monitoring control throughout this chain. Municipalities possess significant autonomy in determining the means and methods to achieve national adaptation objectives, using funds allocated as part of the government’s general municipality budget. This local autonomy helps to explain our findings that reveal more pronounced risk-oriented discourses and practices at the local level, reflecting local public authorities' endeavors to secure resources for implementing interventions tailored to address specific local conditions. In addition to public authorities, our study underscores the influential role of experts and scientists in shaping the discourse surrounding the climate crisis at all governance levels. Taken together, these insights confirm an asymmetrical relationship regarding who informs the debate, whereby experts and scientists wield significant power in defining climate adaptation in risk terms. [:arrow_up_small:](#sec-program)

# Abstracts Posters

#### Distributing responsibility for managing uncertain issues - on what ethical grounds? \| Åsa Knaggård, Lund University, Sweden {#abs-knaggard}

abstract

#### Translating predictive distributions into informative priors \| Isha Saxena, Durham University, UK {#abs-saxena}

Current models oversimplify failure and repair processes, hindering accurate maintenance scheduling and cost reduction efforts. This research uses Supervisory Control and Data Acquisition (SCADA) data to develop a more precise reliability analysis framework. The study uses Maximum Likelihood Estimation (MLE), and Bayesian Parameter Expectation to model times to failure and times to repair data for wind turbine components. Bayesian methods are particularly advantageous in handling uncertainty inherent in complex systems. However, using informative priors presents a challenge, given the complex nature of turbine failures as well as lack of data. Bayesian inference techniques are utilized to compute posterior distributions, capturing updated beliefs about model parameters after observing SCADA data. Computational complexity arises due to the large datasets and intricate model specifications. Furthermore, the study extends beyond individual component failures to consider the interactions and dependencies within wind turbine systems. The research aims to address the following questions: How can failure and repair processes be modelled more accurately using a different statistical model? How do the new statistical models differ from the existing models?

The poster presentation will showcase the methodology, challenges, and preliminary findings of the Bayesian Parameter Estimation and Maximum Likelihood Estimation. Validation has been carried out by using prior and posterior predictive methods. By bridging the gap between theoretical models and real-world data, this research contributes to the advancement of offshore wind turbine reliability assessment and supports the UK's transition towards a sustainable energy landscape. [:arrow_up_small:](#sec-program)

#### Prioritising Risk Education in Secondary Schools: Perspectives, Practicalities, and Progress \| Sarah Duckett, King's College London, UK {#abs-duckett}

As society grapples with increasingly complex risks, the imperative for effective risk education in secondary schools becomes paramount. While the literature advocates for integrating risk education into curricula, there exists a significant gap in defining its scope, content, and pedagogical strategies. This study addresses this gap through a multi-phased research approach.

This research comprises of four phases. Phase 1 involves interviews with risk experts to delineate key areas of risk pertinent to secondary school education. Phase 2 engages teacher educators to assess the current status of risk education in UK secondary schools and evaluate recommendations from Phase 1. Phase 3 delves into the perspectives of secondary school teachers regarding their understanding and implementation of risk education. Finally, Phase 4 integrates findings with a review of teaching resources to propose structured approaches for curriculum integration, timing, presentation, and assessment.

This research is crucial as despite longstanding calls for increased risk education, progress has been hindered by vague recommendations and lack of consensus on implementation. By synthesising insights from risk experts, teacher educators, and teachers, this study aims to provide clarity and operational guidance for effective risk education in secondary schools. The findings promise to inform policy, curriculum design, and professional development initiatives, facilitating a more comprehensive and impactful approach to risk education. [:arrow_up_small:](#sec-program)
